version: "3.7"
services:
  web-server:
    build: ./
    image: aiwarsoc/front-end:debug
    volumes:
      - "./server:/home/web_user/server"
    ports:
      - "80:8080"
    networks:
      - database
    environment:
      DEBUG: "True"
    secrets:
      - secret_key
  database:
    image: aiwarssoc/database
    volumes:
      - "./debug/database:/database"
    networks:
      database:
        aliases:
          - database
    environment:
      DEBUG: "True"
      INITIAL_SCORE: 1000
      SCORE_TURBULENCE_MILLIS: 5000
      HEALTH_BUFFER: 100
networks:
  database:
secrets:
  secret_key:
    file: ./debug_secret.txt