version: "3.7"
services:
  web-server:
    build: ./
    image: aiwarsoc/front-end:debug
    ports:
      - "80:8080"
    volumes:
      - "./server:/home/web_user/server"
    networks:
      - database
      - redis
    environment:
      DEBUG: "True"
      TESTING: "True"
      SERVER_NAME: "lvh.me"
      CLIENT_ID: "389788965612-qh4j3n7fh14nfjbg7u1tmlb59mudmobj.apps.googleusercontent.com"
    secrets:
      - secret_key
  database:
    image: aiwarssoc/database
    volumes:
      - "./tmp/database:/database"
      - "./tmp/repositories:/repositories"
    networks:
      database:
        aliases:
          - database
    ports:
      - "8081:8080"
    environment:
      DEBUG: "True"
      INITIAL_SCORE: 1000
      SCORE_TURBULENCE_MILLIS: 5000
      HEALTH_BUFFER: 100
      MAX_REPO_SIZE_BYTES: 10000000
  redis:
    image: redis
    volumes:
      - "./tmp/redis:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
networks:
  database:
  redis:
secrets:
  secret_key:
    file: ./debug_secret.txt