version: "3.7"
services:
  web-server:
    build: ./
    image: aiwarssoc/front-end:debug
    ports:
      - "80:8080"
    volumes:
      - "./server:/home/web_user/server"
      - "./tmp/repositories:/repositories"
      - "./tmp/database:/database"
      - "./debug_config.yml:/home/web_user/server/config.yml"
    networks:
      - database
      - redis
    secrets:
      - secret_key
  redis:
    image: redis
    volumes:
      - "./tmp/redis:/data"
    command: "--appendonly yes"
    networks:
      redis:
        aliases:
          - redis
networks:
  database:
  redis:
secrets:
  secret_key:
    file: ./debug_secret.txt
